[alias]
test-xml = """test
                --test conformance_xml_eduni_misc_invalid
                --test conformance_xml_eduni_errata2e_error
                --test conformance_xml_eduni_errata2e_invalid
                --test conformance_xml_eduni_errata2e_notwf
                --test conformance_xml_eduni_errata2e_valid
                --test conformance_xml_eduni_errata3e_invalid
                --test conformance_xml_eduni_errata3e_notwf
                --test conformance_xml_eduni_errata3e_valid
                --test conformance_xml_eduni_errata4e_error
                --test conformance_xml_eduni_errata4e_invalid
                --test conformance_xml_eduni_errata4e_notwf
                --test conformance_xml_eduni_errata4e_valid
                --test conformance_xml_eduni_misc_notwf
                --test conformance_xml_eduni_namespaces_10_error
                --test conformance_xml_eduni_namespaces_10_invalid
                --test conformance_xml_eduni_namespaces_10_notwf
                --test conformance_xml_eduni_namespaces_10_valid
                --test conformance_xml_eduni_namespaces_11_notwf
                --test conformance_xml_eduni_namespaces_11_valid
                --test conformance_xml_eduni_namespaces_errata1e_notwf
                --test conformance_xml_eduni_xml11_error
                --test conformance_xml_eduni_xml11_invalid
                --test conformance_xml_eduni_xml11_notwf
                --test conformance_xml_eduni_xml11_valid
                --test conformance_xml_ibm11_invalid
                --test conformance_xml_ibm11_notwf
                --test conformance_xml_ibm11_valid
                --test conformance_xml_ibm_error
                --test conformance_xml_ibm_invalid
                --test conformance_xml_ibm_notwf_1
                --test conformance_xml_ibm_notwf_2
                --test conformance_xml_ibm_notwf_3
                --test conformance_xml_ibm_notwf_4
                --test conformance_xml_ibm_notwf_5
                --test conformance_xml_ibm_notwf_6
                --test conformance_xml_ibm_notwf_7
                --test conformance_xml_ibm_notwf_8
                --test conformance_xml_ibm_valid
                --test conformance_xml_oasis_error
                --test conformance_xml_oasis_invalid
                --test conformance_xml_oasis_notwf
                --test conformance_xml_oasis_valid
                --test conformance_xml_sun_error
                --test conformance_xml_sun_invalid
                --test conformance_xml_sun_notwf
                --test conformance_xml_sun_valid
                --test conformance_xml_xmltest_invalid
                --test conformance_xml_xmltest_notwf_ext_sa
                --test conformance_xml_xmltest_notwf_not_sa
                --test conformance_xml_xmltest_notwf_sa
                --test conformance_xml_xmltest_valid_ext_sa
                --test conformance_xml_xmltest_valid_not_sa
                --test conformance_xml_xmltest_valid_sa
                --test conformance_xml_xmltest_valid_sa_canonicalonly
                --features test-conformance-xml"""
test-xmlid = "test  --package xrust --test conformance_xmlid_normwalsh --features test-conformance-xmlid"
